export const PAGE_METADATA_FONT_SIZE_PX = 14;
export const PAGE_METADATA_ROW_HEIGHT_PX = 22;
export const PAGE_METADATA_LINE_HEIGHT_PX = 20;
export const PAGE_METADATA_LABEL_MIN_WIDTH_PX = 42;
export const PAGE_METADATA_LABEL_MAX_WIDTH_PX = 88;
export const PAGE_METADATA_LABEL_RIGHT_GAP_PX = 10;
export const PAGE_METADATA_BOTTOM_GAP_PX = 0;
export const PAGE_METADATA_TABLE_MIN_WIDTH_PX = 320;
export const PAGE_METADATA_TABLE_MAX_WIDTH_PX = 720;
export const PAGE_METADATA_TABLE_WIDTH_RATIO = 1;

export const PAGE_METADATA_LABEL_COLOR = "rgba(55, 53, 47, 0.55)";
export const PAGE_METADATA_VALUE_COLOR = "rgb(55, 53, 47)";
